name: Electron Forge Build (Windows)

on:
  # Запускати робочий процес при створенні нового тегу (релізу)
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Наприклад, v1.0.0

jobs:
  build-win:
    # !!! ЗМІНА: Використовуємо нативний Windows-раннер !!!
    runs-on: windows-latest

    permissions:
      contents: write

    env:
      VITE_SERVER_URL: https://apis.swedka121.com/eduquiz

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm ci --force

      - name: Run Electron Forge Make (Windows)
        shell: powershell
        run: npm run make -- --platform=win32

      - name: List Windows Installer Directory for Debug
        shell: powershell
        run: dir out/make/squirrel.windows

      - name: Find and Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: out/make/squirrel.windows/x64/*.exe

  build-deb:
    name: Build for Debian/Ubuntu
    runs-on: ubuntu-latest

    env:
      VITE_SERVER_URL: https://apis.swedka121.com/eduquiz

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm ci --force

      - name: Run Electron Forge Make (Debian)
        run: npm run make -- --platform=linux

      - name: Find and Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-installer
          path: out/make/deb/x64/*.deb

  downloadAndRelease:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    needs: [build-win, build-deb]

    steps:
      - name: Download All Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release/

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: release/**/*.*
          make_latest: true
          name: Release EduQuiz ${{github.ref}}
